{{ if .Values.plgx.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polylogyx.fullname" . }}-ui
  labels: {{- include "polylogyx.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "polylogyx.fullname" . }}-ui
  {{ if .Values.plgx.ui.service.annotations }}
  annotations: {{- toYaml .Values.plgx.ui.service.annotations | nindent 4 }}
  {{ end }}
spec:
  type: {{ .Values.plgx.ui.service.type }}
  {{- if eq .Values.plgx.ui.service.type "LoadBalancer" }}
  {{- if .Values.plgx.ui.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.plgx.ui.service.loadBalancerIP }}
  {{- end }}
  {{- end }}
  {{- if (or (eq .Values.plgx.ui.service.type "LoadBalancer") (eq .Values.plgx.ui.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.plgx.ui.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5001
  selector: {{- include "polylogyx.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "polylogyx.fullname" . }}-ui
{{ end }}