{{ if .Values.plgx.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "polylogyx.fullname" . }}-ingress
  labels: {{- include "polylogyx.labels.standard" . | nindent 4 }}
  {{ if toYaml .Values.plgx.ingress.annotations }}
  annotations: {{ toYaml .Values.plgx.ingress.annotations | nindent 4 }}
  {{ end }}
spec:
  rules:
  - host: {{ .Values.plgx.ingress.hostname }}
    http:
      paths:
      # esp paths
      {{ if .Values.plgx.esp.enabled }}
      - path: /config
        pathType: Prefix
        backend:
          service:
            name: {{ template "polylogyx.fullname" . }}-esp
            port: 
              number: 6000
      - path: /enroll
        pathType: Prefix
        backend:
          service:
            name: {{ template "polylogyx.fullname" . }}-esp
            port: 
              number: 6000
      - path: /distributed/write
        pathType: Prefix
        backend:
          service:
            name: {{ template "polylogyx.fullname" . }}-esp
            port: 
              number: 6000
      - path: /distributed/read
        pathType: Prefix
        backend:
          service:
            name: {{ template "polylogyx.fullname" . }}-esp
            port: 
              number: 6000
      - path: /log
        pathType: Prefix
        backend:
          service:
            name: {{ template "polylogyx.fullname" . }}-esp
            port: 
              number: 6000
      - path: /start_uploads
        pathType: Prefix
        backend:
          service:
            name: {{ template "polylogyx.fullname" . }}-esp
            port: 
              number: 6000
      - path: /upload_blocks
        pathType: Prefix
        backend:
          service:
            name: {{ template "polylogyx.fullname" . }}-esp
            port: 
              number: 6000
      {{ end }}
      # esp-ui paths
      {{ if .Values.plgx.ui.enabled }}
      - path: /services
        pathType: Prefix
        backend:
          service:
            name: {{ template "polylogyx.fullname" . }}-ui
            port:
              number: 5000
      - path: /distributed/result
        pathType: Prefix
        backend:
          service:
            name: {{ template "polylogyx.fullname" . }}-ui
            port: 
              number: 5000
      {{ end }}
      # esp-fileserver paths
      {{ if .Values.plgx.fileserver.enabled }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "polylogyx.fullname" . }}-fileserver
            port:
              number: 80
      {{ end }}
  {{ if .Values.plgx.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.plgx.ingress.hostname }}
    secretName: {{ .Values.plgx.ingress.tls.secretName }}
  {{ end }}
{{ end }}
